export const PATH = {
  HOME: '/',
  CATEGORY: '/category',
  HISTORY: '/history',
  LIKED: '/liked',
  CHAT: '/chat',
  CHATROOM: '/chat/:roomId',
  ACCOUNT: '/account',
  DETAIL: '/product/:id',
  ADD: '/add',
  JOIN: '/join',
  CALLBACK: '/callback/:provider',
  FALLBACK: '*',
  GOBACK: -1,
};